name: TERRAFORM PROJ

on:
  push:
    # branches: [ master ]
    tags:
     - v1.**

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build with Maven proj
      run: mvn package
    - name: Set Relase version
      id: vars
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: build docker image and push to ecr repo
      run: |
         docker build -t ${{ secrets.ECR_REPO_NAME }}/spring:${{ env.RELEASE_VERSION  }} .
         $(aws ecr get-login --no-include-email --region ap-south-1)
         docker push ${{ secrets.ECR_REPO_NAME }}/spring:${{ env.RELEASE_VERSION }}
 
